// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Header": {
    "topBarText": "Want to stay up to date?",
    "topBarLink": "Subscribe to newsletter",
    "aboutUs": "About us",
    "forCompanies": "For companies",
    "forPartners": "For partners",
    "exploreNetwork": "Explore network",
    "club": "Club",
    "contact": "Contact",
    "faqNav": "FAQ",
    "followUs": "Follow us",
    "comingSoon": "Coming soon"
  },
  "Footer": {
    "aboutUs": "About us",
    "forCompanies": "For companies",
    "forPartners": "For partners",
    "exploreNetwork": "Explore network",
    "club": "Club",
    "faq": "FAQ",
    "contact": "Contact",
    "faqNav": "FAQ",
    "followUs": "Follow us",
    "resources": "Resources",
    "comingSoon": "Coming soon",
    "termsConditions": "Terms and conditions",
    "privacyPolicy": "Privacy policy",
    "contactUs": "Contact us",
    "rights": "All rights reserved"
  },
  "Error": {
    "description": "<p>We've unfortunately encountered an error.</p><p>You can try to <retry>reload the page</retry> you were visiting.</p>",
    "title": "Something went wrong!"
  },
  "AboutUs": {
    "fitpassStartsSerbia": "Fitpass begins its’ journey in Serbia!",
    "fitpassBosnia": "Fitpass expands to Bosnia!",
    "bigYearFitpass": "A big year for Fitpass! Launch of the Fitpass app, becoming a part of Up Group, the start of Fitpass Georgia.",
    "fitpassCg": "New markets alert! Fitpass is coming to Montenegro, Greece and Moldova - SOON!"
  },
  "ExploreNetworkPage": {
    "fitpassNetworkPart1": "Fitpass",
    "fitpassNetworkPart2": "network",
    "searchGyms": "Search gyms & studios near you"
  },
  "ForCompanies": {
    "source": "*Resource:",
    "recaptchaValidationError": "Please verify that you are human",
    "companyNumberValid": "Please enter a valid TIN.",
    "requiredFieldsMessage": "Please fill out all required fields.",
    "validEmail": "Please enter a valid email address.",
    "phoneNumberValid": "Please enter a valid phone number.",
    "acceptTerms": "Please accept the Terms and conditions and Privacy policy.",
    "formErrorMessage": "Something went wrong. Please try again later.",
    "agreeToReceiveNews": "I agree to receive news and updates from Fitpass"
  },
  "ForPartners": {
    "recaptchaValidationError": "Please verify that you are human",
    "agreeToReceiveNews": "I agree to receive news and updates from Fitpass"
  },
  "SearchResultsExploreNetworkFiltersSection": {
    "locationName": "Location name",
    "cityInput": "City",
    "cityArea": "City area",
    "clear": "Clear",
    "apply": "Apply",
    "disciplines": "Disciplines",
    "loading": "Loading..."
  },
  "SearchResultsVenues": {
    "openingAt": "Opening at",
    "openingHours": "Opening hours",
    "noWorkTime": "No work time",
    "noSearchResults": "No search results",
    "closingAt": "Closing at"
  },
  "IndexPage": {
    "description": "This is a basic example that demonstrates the usage of <code>next-intl</code> with the Next.js App Router. Try changing the locale in the top right corner and see how the content changes.",
    "title": "next-intl example"
  },
  "LocaleLayout": {
    "title": "next-intl example"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, cg {CG} en {EN} sr {SR} fr {FR} other {Unknown}}"
  },
  "Manifest": {
    "name": "next-intl example"
  },
  "Navigation": {
    "home": "Home",
    "pathnames": "Pathnames"
  },
  "NotFoundPage": {
    "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
    "title": "Page not found"
  },
  "PageLayout": {
    "links": {
      "docs": {
        "description": "Learn more about next-intl in the official docs.",
        "href": "https://next-intl.dev",
        "title": "Docs"
      },
      "source": {
        "description": "Browse the source code of this example on GitHub.",
        "href": "https://github.com/amannn/next-intl/tree/main/examples/example-app-router",
        "title": "Source code"
      }
    }
  },
  "PathnamesPage": {
    "description": "<p>The pathnames are internationalized too.</p><p>If you're using the default language English, you'll see <code>/en/pathnames</code> in the browser address bar on this page.</p><p>If you change the locale to German, the URL is localized accordingly (<code>/de/pfadnamen</code>).</p>",
    "title": "Pathnames"
  }
};
export default messages;