// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Common": {
    "useCookies": "We use cookies to ensure you get the best experience on our website.",
    "clickAccept": "Click accept to accept all cookies or click settings to manage your preferences.",
    "accept": "Accept",
    "cookiesSettings": "Cookies settings"
  },
  "MetaDataGeneric": {
    "siteName": "Fitpass",
    "title": "Fitpass | One pass fits all",
    "description": "Fitpass is a prominent brand in the field of sports and recreation, founded in 2014 in Serbia. The Fitpass concept brought a revolution to fitness by allowing users to access a wide range of sports facilities and activities across the country with a single membership."
  },
  "AboutUsMetaData": {
    "title": "Fitpass | About us"
  },
  "ClubMetaData": {
    "title": "Fitpass | Club"
  },
  "ContactMetaData": {
    "title": "Fitpass | Contact"
  },
  "ExploreNetworkMetaData": {
    "title": "Fitpass | Explore network"
  },
  "FaqMetaData": {
    "title": "Fitpass | FAQ"
  },
  "ForCompaniesMetaData": {
    "title": "Fitpass | For companies"
  },
  "ForPartnersMetaData": {
    "title": "Fitpass | For partners"
  },
  "Header": {
    "topBarText": "Want to stay up to date?",
    "topBarLink": "Subscribe to newsletter",
    "aboutUs": "About us",
    "forCompanies": "For companies",
    "forPartners": "For partners",
    "exploreNetwork": "Explore network",
    "club": "Club",
    "contact": "Contact",
    "faqNav": "FAQ",
    "followUs": "Follow us",
    "comingSoon": "Coming soon"
  },
  "Footer": {
    "aboutUs": "About us",
    "forCompanies": "For companies",
    "forPartners": "For partners",
    "exploreNetwork": "Explore network",
    "club": "Club",
    "faq": "FAQ",
    "contact": "Contact",
    "faqNav": "FAQ",
    "followUs": "Follow us",
    "resources": "Resources",
    "comingSoon": "Coming soon",
    "termsConditions": "Terms and conditions",
    "privacyPolicy": "Privacy policy",
    "contactUs": "Contact us",
    "rights": "All rights reserved"
  },
  "AboutUs": {
    "fitpassStartsSerbia": "Fitpass begins its’ journey in Serbia!",
    "fitpassBosnia": "Fitpass expands to Bosnia!",
    "bigYearFitpass": "A big year for Fitpass! Launch of the Fitpass app, becoming a part of Up Group, the start of Fitpass Georgia.",
    "fitpassCg": "New markets alert! Fitpass is coming to Montenegro, Greece and Moldova - SOON!"
  },
  "ForCompanies": {
    "source": "*Resource:",
    "recaptchaValidationError": "Please verify that you are human",
    "companyNumberValid": "Please enter a valid TIN.",
    "requiredFieldsMessage": "Please fill out all required fields.",
    "validEmail": "Please enter a valid email address.",
    "phoneNumberValid": "Please enter a valid phone number.",
    "acceptTerms": "Please accept the Terms and conditions and Privacy policy.",
    "formErrorMessage": "Something went wrong. Please try again later.",
    "agreeToReceiveNews": "I agree to receive news and updates from Fitpass",
    "formSuccessMessage": "Your request is successfully sent to Fitpass team. Our team will reach out to you in short notice.",
    "submitButton": "Submit",
    "mandatoryFields": "Mandatory fields",
    "agreeOnFitpass": "I agree on Fitpass",
    "termsAndConditions": "Terms and conditions",
    "privacyPolicy": "Privacy policy",
    "and": "and",
    "companyName": "Company name*",
    "companyNumber": "TIN*",
    "pibTooltip": "Enter the company number (TIN)",
    "address": "Address*",
    "nameSurname": "Name and surname*",
    "phoneNumber": "Phone number*",
    "yourPosition": "Your role*",
    "yourTeamSize": "Your team size*"
  },
  "ForPartners": {
    "recaptchaValidationError": "Please verify that you are human",
    "agreeToReceiveNews": "I agree to receive news and updates from Fitpass",
    "requiredFieldsMessage": "Please fill out all required fields.",
    "validEmail": "Please enter a valid email address.",
    "phoneNumberValid": "Please enter a valid phone number.",
    "acceptTerms": "Please accept the Terms and conditions and Privacy policy.",
    "formErrorMessage": "Something went wrong. Please try again later.",
    "formSuccessMessage": "Your request is successfully sent to Fitpass team. Our team will reach out to you in short notice.",
    "venueName": "Venue name*",
    "venueType": "Venue type*",
    "address": "Address*",
    "nameSurname": "Name and surname*",
    "email": "Email*",
    "phoneNumber": "Phone number*",
    "terms": "Terms and conditions*",
    "agreeOnFitpass": "I agree on Fitpass",
    "termsAndConditions": "Terms and conditions",
    "privacyPolicy": "Privacy policy",
    "and": "and",
    "submitButton": "Submit",
    "mandatoryFields": "Mandatory fields",
    "gym": "Gym",
    "pool": "Pool",
    "spa": "Spa and sauna",
    "sportComplex": "Sport complex",
    "kidsActivities": "Kids activities",
    "groupClasses": "Group classes",
    "other": "Other"
  },
  "Faq": {
    "faqHeaderLine1": "Frequently",
    "faqHeaderLine2": "Asked Questions",
    "faqHeaderText": "Find answers to the most common questions about Fitpass.",
    "content": "Content",
    "whatIsFitpass": "What is Fitpass?",
    "facilities": "Facilities",
    "howToGetFitpass": "How to get Fitpass?",
    "fitpassCompany": "Fitpass Company",
    "buyingFitpass": "Buying Fitpass",
    "club": "Club"
  },
  "Contact": {
    "weGotYourMessage": "We got your message",
    "thanksForReachingOut": "Thanks for reaching out!",
    "stayTuned": "Stay tuned!",
    "recaptchaValidationError": "Please verify that you are human",
    "recaptchaError": "Something went wrong. Please try again later.",
    "requiredFieldsMessage": "Please fill out all required fields.",
    "validEmail": "Please enter a valid email address.",
    "selectDepartment": "Please select at least one department.",
    "formErrorMessage": "Something went wrong. Please try again later.",
    "fitpassForIndividuals": "Fitpass for individuals",
    "employeeBenefits": "Employee benefits",
    "businessCollaborations": "Business collaborations",
    "otherInquires": "Other inquires",
    "name": "Name",
    "surname": "Surname",
    "email": "Email",
    "phone": "Phone",
    "message": "Message",
    "reset": "Reset",
    "send": "Send"
  },
  "Club": {
    "readyToExploreDiscounts": "Ready to explore discounts",
    "allDiscounts": "All discounts",
    "checkOurMore": "Check our more",
    "learnMore": "Learn more"
  },
  "ExploreNetworkPage": {
    "fitpassNetworkPart1": "Fitpass",
    "fitpassNetworkPart2": "network",
    "searchGyms": "Search gyms & studios near you",
    "pleaseSelectAtLeastOneFilter": "Please select at least one filter",
    "locationName": "Location name",
    "cityInput": "City",
    "cityArea": "City area",
    "clear": "Clear",
    "apply": "Apply",
    "disciplines": "Disciplines",
    "loading": "Loading...",
    "showOnMap": "Show on map",
    "openingAt": "Opening at",
    "openingHours": "Opening hours",
    "noWorkTime": "No work time",
    "noSearchResults": "No search results",
    "closingAt": "Closing at",
    "open": "Open",
    "closed": "Closed",
    "today": "Today",
    "monday": "Monday",
    "tuesday": "Tuesday",
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "sunday": "Sunday",
    "favorites": "Favorites",
    "in": "In",
    "noviSad": "Novi Sad",
    "family": "Family",
    "friendly": "Friendly",
    "teamBuilding": "Team building",
    "teamBuildingActivities": "Team building activities",
    "special": "Special",
    "offer": "Offer",
    "belgrade": "Belgrade",
    "workHours": "Work hours",
    "readComments": "Read comments",
    "readMore": "Read more",
    "readLess": "Read less",
    "schedule": "Schedule",
    "prevDay": "Previous day",
    "nextDay": "Next day",
    "noActivities": "No activities",
    "commentsAndGrades": "Comments and grades",
    "equipment": "Equipment",
    "stuff": "Stuff",
    "hygiene": "Hygiene",
    "rooms": "Rooms",
    "howToGrade": "How to grade",
    "howToGradeAnswer": "If you want to rate a facility, it is enough to go to a training session at the desired facility and at the end of the day you will receive an e-mail (to the address you left during registration) with instructions on how to rate the facility"
  },
  "Manifest": {
    "name": "next-intl example"
  },
  "NotFoundPage": {
    "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
    "title": "Page not found"
  },
  "Error": {
    "description": "We've unfortunately encountered an error. Please try again later.",
    "title": "Something went wrong!"
  }
};
export default messages;